workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    environment:
      flutter: "3.24.5"
      xcode: latest

    scripts:
      - flutter pub get
      - flutter build ios --simulator

    artifacts:
      - build/ios/iphonesimulator/*.app
